// demos/vue-supabase-todolist/src/views/Register.vue
<template>
  <LoginDetailsWidget
    class="d-flex justify-center"
    title="Register"
    submitTitle="Register"
    :secondaryActions="actions"
    :errorMessage="errorMessage"
    @submit="onRegister"
  />
</template>

<script setup lang="ts">
import LoginDetailsWidget from '@/components/widgets/LoginDetailsWidget.vue';
import { DEFAULT_ENTRY_ROUTE, LOGIN_ROUTE } from '@/plugins/router';
import { supabase } from '@/plugins/supabase';
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();
const errorMessage = ref<string>('');

const onRegister = async (form: { email: string; password: string }) => {
  if (!supabase.ready) {
    throw new Error('Supabase has not been initialized yet');
  }
  errorMessage.value = '';

  const {
    data: { session },
    error
  } = await supabase.client.auth.signUp({ email: form.email, password: form.password });

  if (error) {
    errorMessage.value = (error as any).message || 'unknown failure';
    throw new Error(error.message);
  }

  if (session) {
    supabase.updateSession(session);
    router.push(DEFAULT_ENTRY_ROUTE);
    return;
  }

  alert('Registration successful, please login');
  router.push(LOGIN_ROUTE);
};

const actions = [
  {
    title: 'BACK',
    onClick: () => {
      router.push(LOGIN_ROUTE);
    }
  }
];
</script>

// demos/react-supabase-todolist/src/app/auth/register/page.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useSupabase } from '../../../components/providers/SystemProvider';
import { LoginDetailsWidget } from '../../../components/widgets/LoginDetailsWidget';
import { DEFAULT_ENTRY_ROUTE, LOGIN_ROUTE } from '../../router';

export default function RegisterPage() {
  const supabase = useSupabase();
  const navigate = useNavigate();

  return (
    <LoginDetailsWidget
      title="Register"
      submitTitle="Register"
      onSubmit={async ({ email, password }) => {
        if (!supabase) {
          throw new Error('Supabase has not been initialized yet');
        }
        const {
          data: { session },
          error
        } = await supabase.client.auth.signUp({ email, password });
        if (error) {
          throw new Error(error.message);
        }

        if (session) {
          supabase.updateSession(session);
          navigate(DEFAULT_ENTRY_ROUTE);
          return;
        }

        // TODO better dialog
        alert('Registration successful, please login');
        navigate(LOGIN_ROUTE);
      }}
      secondaryActions={[{ title: 'Back', onClick: () => navigate(LOGIN_ROUTE) }]}
    />
  );
}
