// demos/electron-supabase-todolist/src/app/auth/login/page.tsx
import React from 'react';
import { LoginDetailsWidget } from '../../../components/widgets/LoginDetailsWidget.jsx';
import { useSupabase } from '../../../components/providers/SystemProvider.jsx';
import { useNavigate } from 'react-router-dom';
import { DEFAULT_ENTRY_ROUTE } from '../../../app/router.jsx';

export default function LoginPage() {
  const supabase = useSupabase();
  const navigate = useNavigate();

  return (
    <LoginDetailsWidget
      title="Login"
      submitTitle="Login"
      onSubmit={async (values) => {
        if (!supabase) {
          throw new Error('Supabase has not been initialized yet');
        }
        await supabase.login(values.email, values.password);
        navigate(DEFAULT_ENTRY_ROUTE);
      }}
      secondaryActions={[
        {
          title: 'Register',
          onClick: () => {
            navigate('/auth/register');
          }
        }
      ]}
    />
  );
}

// demos/vue-supabase-todolist/src/views/Login.vue
<template>
    <div>login</div>
    <div>
        <!-- <LoginDetailsWidget
      title="Login"
      submitTitle="Login"
      onSubmit={async (values) => {
        if (!supabase) {
          throw new Error('Supabase has not been initialized yet');
        }
        await supabase.login(values.email, values.password);
        navigate(DEFAULT_ENTRY_ROUTE);
      }}
      secondaryActions={[{
        title: 'Register', onClick: () => {
          navigate('/auth/register');
        }
      }]}
    /> -->
    </div>
</template>

<script setup>
</script>
<!-- <LoginDetailsWidget
      title="Login"
      submitTitle="Login"
      onSubmit={async (values) => {
        if (!supabase) {
          throw new Error('Supabase has not been initialized yet');
        }
        await supabase.login(values.email, values.password);
        navigate(DEFAULT_ENTRY_ROUTE);
      }}
      secondaryActions={[{
        title: 'Register', onClick: () => {
          navigate('/auth/register');
        }
      }]}
    /> -->
