// demos/diagnostics-app/src/app/views/sql-console.tsx
import React from 'react';
import { usePowerSyncWatchedQuery } from '@journeyapps/powersync-react';
import { Box, Button, Grid, TextField, styled } from '@mui/material';
import { DataGrid } from '@mui/x-data-grid';
import { NavigationPage } from '@/components/navigation/NavigationPage';

const DEFAULT_QUERY = `SELECT name FROM ps_buckets`;

export default function SQLConsolePage() {
  const inputRef = React.useRef<HTMLInputElement>();
  const [query, setQuery] = React.useState(DEFAULT_QUERY);
  const querySQLResult = usePowerSyncWatchedQuery(query);

  const queryDataGridResult = React.useMemo(() => {
    const firstItem = querySQLResult?.[0];

    return {
      columns: firstItem
        ? Object.keys(firstItem).map((field) => ({
            field,
            flex: 1
          }))
        : [],
      rows: querySQLResult
    };
  }, [querySQLResult]);

  return (
    <NavigationPage title="SQL Console">
      <S.MainContainer>
        <S.CenteredGrid container>
          <S.CenteredGrid item xs={12} md={10}>
            <TextField
              inputRef={inputRef}
              fullWidth
              label="Query"
              defaultValue={DEFAULT_QUERY}
              onKeyDown={(e) => {
                const inputValue = inputRef.current?.value;
                if (e.key == 'Enter' && inputValue) {
                  setQuery(inputValue);
                }
              }}
            />
          </S.CenteredGrid>
          <S.CenteredGrid item xs={12} md={2}>
            <Button
              sx={{ margin: '10px' }}
              variant="contained"
              onClick={() => {
                const queryInput = inputRef?.current?.value;
                if (queryInput) {
                  setQuery(queryInput);
                }
              }}>
              Execute Query
            </Button>
          </S.CenteredGrid>
        </S.CenteredGrid>

        {queryDataGridResult ? (
          <S.QueryResultContainer>
            {queryDataGridResult.columns ? (
              <DataGrid
                autoHeight={true}
                rows={queryDataGridResult.rows?.map((r, index) => ({ ...r, id: r.id ?? index })) ?? []}
                columns={queryDataGridResult.columns}
                initialState={{
                  pagination: {
                    paginationModel: {
                      pageSize: 20
                    }
                  }
                }}
                pageSizeOptions={[20]}
                disableRowSelectionOnClick
              />
            ) : null}
          </S.QueryResultContainer>
        ) : null}
      </S.MainContainer>
    </NavigationPage>
  );
}

namespace S {
  export const MainContainer = styled(Box)`
    padding: 20px;
  `;

  export const QueryResultContainer = styled(Box)`
    margin-top: 40px;
  `;

  export const CenteredGrid = styled(Grid)`
    display: flex;
    justify-content: center;
    align-items: center;
  `;
}

// demos/vue-supabase-todolist/src/views/SqlConsole.vue
<template>
  <!-- <navigation-panel title="SQL Console"> -->
  <!-- <v-container>
      <v-row justify="center">
        <v-col cols="12" md="10">
          <v-text-field v-model="inputText" label="Query" outlined dense @keyup.enter="executeQuery"></v-text-field>
        </v-col>
        <v-col cols="12" md="2">
          <v-btn color="primary" @click="executeQuery">Execute Query</v-btn>
        </v-col>
      </v-row>
      <v-container v-if="queryDataGridResult.columns.length > 0" class="mt-4">
        <v-data-table :columns="queryDataGridResult.columns" :items="queryDataGridResult.rows"
          :items-per-page="20"></v-data-table>
      </v-container>
    </v-container> -->
  <!-- </navigation-panel> -->
  <div> SQL CONSOLE
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
// import NavigationPanel from '@/components/navigation/NavigationPanel.vue'; // Update the path as necessary
import { usePowerSyncWatchedQuery } from '@journeyapps/powersync-vue';

const query = ref('SELECT * FROM lists');
const inputText = ref('')
const executeQuery = () => {
  query.value = inputText.value;
};
const { data: querySQLResult } = usePowerSyncWatchedQuery(query.value);

const queryDataGridResult = computed(() => {
  const firstItem = querySQLResult.value?.[0];
  return {
    columns: firstItem ? Object.keys(firstItem).map((field) => ({ text: field, value: field })) : [],
    rows: querySQLResult.value ?? [],
  };
});
</script>
