// demos/react-supabase-todolist-tanstackdb/src/app/views/layout.tsx
import { LOGIN_ROUTE, SQL_CONSOLE_ROUTE, TODO_LISTS_ROUTE } from '@/app/router';
import { useNavigationPanel } from '@/components/navigation/NavigationPanelContext';
import { useSupabase } from '@/components/providers/SystemProvider';
import ChecklistRtlIcon from '@mui/icons-material/ChecklistRtl';
import ExitToAppIcon from '@mui/icons-material/ExitToApp';
import MenuIcon from '@mui/icons-material/Menu';
import NorthIcon from '@mui/icons-material/North';
import SignalWifiOffIcon from '@mui/icons-material/SignalWifiOff';
import SouthIcon from '@mui/icons-material/South';
import TerminalIcon from '@mui/icons-material/Terminal';
import WifiIcon from '@mui/icons-material/Wifi';
import {
  AppBar,
  Box,
  Divider,
  Drawer,
  IconButton,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Toolbar,
  Typography,
  styled
} from '@mui/material';
import { usePowerSync, useStatus } from '@powersync/react';
import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function ViewsLayout({ children }: { children: React.ReactNode }) {
  const powerSync = usePowerSync();
  const status = useStatus();
  const supabase = useSupabase();
  const navigate = useNavigate();

  const [openDrawer, setOpenDrawer] = React.useState(false);
  const { title } = useNavigationPanel();

  const [connectionAnchor, setConnectionAnchor] = React.useState<null | HTMLElement>(null);

  const NAVIGATION_ITEMS = React.useMemo(
    () => [
      {
        path: SQL_CONSOLE_ROUTE,
        title: 'SQL Console',
        icon: () => <TerminalIcon />
      },
      {
        path: TODO_LISTS_ROUTE,
        title: 'TODO Lists',
        icon: () => <ChecklistRtlIcon />
      },
      {
        path: LOGIN_ROUTE,
        title: 'Sign Out',
        beforeNavigate: async () => {
          await powerSync.disconnectAndClear();
          await supabase?.client.auth.signOut();
        },
        icon: () => <ExitToAppIcon />
      }
    ],
    [powerSync, supabase]
  );

  return (
    <S.MainBox>
      <S.TopBar position="static">
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
            onClick={() => setOpenDrawer(!openDrawer)}>
            <MenuIcon />
          </IconButton>
          <Box sx={{ flexGrow: 1 }}>
            <Typography>{title}</Typography>
          </Box>
          <NorthIcon sx={{ marginRight: '-10px' }} color={status?.uploading ? 'primary' : 'inherit'} />
          <SouthIcon color={status?.downloading ? 'primary' : 'inherit'} />
          <Box
            sx={{ cursor: 'pointer' }}
            onClick={(event) => {
              setConnectionAnchor(event.currentTarget);
            }}>
            {status?.connected ? <WifiIcon /> : <SignalWifiOffIcon />}
          </Box>
          {/* Allows for manual connection and disconnect for testing purposes */}
          <Menu
            id="connection-menu"
            anchorEl={connectionAnchor}
            open={Boolean(connectionAnchor)}
            onClose={() => setConnectionAnchor(null)}>
            {status?.connected || status?.connecting ? (
              <MenuItem
                onClick={(event) => {
                  setConnectionAnchor(null);
                  powerSync.disconnect();
                }}>
                Disconnect
              </MenuItem>
            ) : supabase ? (
              <MenuItem
                onClick={(event) => {
                  setConnectionAnchor(null);
                  powerSync.connect(supabase);
                }}>
                Connect
              </MenuItem>
            ) : null}
          </Menu>
        </Toolbar>
      </S.TopBar>
      <Drawer anchor={'left'} open={openDrawer} onClose={() => setOpenDrawer(false)}>
        <S.PowerSyncLogo alt="PowerSync Logo" width={250} height={100} src="/powersync-logo.svg" />
        <Divider />
        <List>
          {NAVIGATION_ITEMS.map((item) => (
            <ListItem key={item.path}>
              <ListItemButton
                onClick={async () => {
                  await item.beforeNavigate?.();
                  navigate(item.path);
                  setOpenDrawer(false);
                }}>
                <ListItemIcon>{item.icon()}</ListItemIcon>
                <ListItemText primary={item.title} />
              </ListItemButton>
            </ListItem>
          ))}
        </List>
      </Drawer>
      <S.MainBox>{children}</S.MainBox>
    </S.MainBox>
  );
}

namespace S {
  export const MainBox = styled(Box)`
    flex-grow: 1;
  `;

  export const TopBar = styled(AppBar)`
    margin-bottom: 20px;
  `;

  export const PowerSyncLogo = styled('img')`
    max-width: 250px;
    max-height: 250px;
    object-fit: contain;
    padding: 20px;
  `;
}

// demos/vue-supabase-todolist/src/views/layouts/Layout.vue
<template>
  <v-app-bar app class="pr-6">
    <v-app-bar-nav-icon @click="toggleDrawer"></v-app-bar-nav-icon>
    <h1 class="ml-5 text-subtitle-1 font-weight-bold">{{ title }}</h1>
    <v-spacer />
    <div class="d-flex">
      <v-icon
        :color="syncStatus.uploading ? 'primary' : 'inherit'"
        class="mr-n2 pa-0"
        icon="mdi-arrow-up"
      />

      <v-icon :color="syncStatus.downloading ? 'primary' : 'inherit'" icon="mdi-arrow-down" />
      <v-icon :icon="syncStatus.connected ? 'mdi-wifi' : 'mdi-wifi-strength-off'" />
    </div>
  </v-app-bar>

  <v-navigation-drawer v-model="openDrawer" class="bg-surface-light">
    <img alt="PowerSync Logo" class="pa-5" width="250px" height="100" src="@/assets/powersync-logo.svg" />
    <v-divider></v-divider>
    <v-list>
      <v-list-item v-for="item in NAVIGATION_ITEMS" :key="item.path" @click="navigateTo(item)">
        <template v-slot:prepend>
          <v-icon :icon="item.icon"></v-icon>
        </template>

        <v-list-item-title class="text-left">{{ item.title }}</v-list-item-title>
      </v-list-item>
    </v-list>
  </v-navigation-drawer>

  <v-container class="pa-0" fluid>
    <router-view />
  </v-container>
</template>

<script setup lang="ts">
import { powerSync } from '@/plugins/powerSync';
import { LOGIN_ROUTE, SQL_CONSOLE_ROUTE, TODO_LISTS_ROUTE } from '@/plugins/router';
import { supabase } from '@/plugins/supabase';
import { computed, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { pageSubtitle } from '@/main';
import { useStatus } from '@powersync/vue';

const openDrawer = ref(false);
const syncStatus = useStatus();
const router = useRouter();
const route = useRoute();

const title = computed(() => (route.name?.toString() || 'unknown') + pageSubtitle.value);

// Equivalent navigation items
const NAVIGATION_ITEMS = [
  {
    path: SQL_CONSOLE_ROUTE,
    title: 'SQL Console',
    icon: 'mdi-console'
  },
  {
    path: TODO_LISTS_ROUTE,
    title: 'TODO Lists',
    icon: 'mdi-format-list-checks'
  },
  {
    path: LOGIN_ROUTE,
    title: 'Sign Out',
    beforeNavigate: async () => {
      // Logic to disconnect and clear before navigating
      await powerSync.disconnectAndClear();
      await supabase.client.auth.signOut();
    },
    icon: 'mdi-exit-to-app'
  }
];

const toggleDrawer = () => {
  openDrawer.value = !openDrawer.value;
};

const navigateTo = async (item: (typeof NAVIGATION_ITEMS)[0]) => {
  if (item.beforeNavigate) await item.beforeNavigate();
  router.push(item.path);
  openDrawer.value = false;
};
</script>
