// demos/vue-supabase-todolist/src/views/TodoLists.vue
<template>
  <TodoListsWidget />
  <v-dialog v-model="showPrompt" width="300" opacity="0.5" scrim="black">
    <v-card title="Create Todo List" class="bg-surface-light">
      <v-card-text>
        Enter a name for a new todo list
        <v-text-field
          autofocus
          color="primary"
          hide-details
          class="mt-3"
          v-model="listName"
          variant="outlined"
          label="List Name"
        />
      </v-card-text>

      <v-card-actions>
        <v-spacer></v-spacer>

        <v-btn text="Cancel" color="primary" @click="setShowPrompt(false)" />
        <v-btn text="Create" color="primary" @click="submit" />
      </v-card-actions>
    </v-card>
  </v-dialog>
  <Fab @click="setShowPrompt(true)" />
</template>

<script setup lang="ts">
import TodoListsWidget from '@/components/widgets/TodoListsWidget.vue';
import { LISTS_TABLE } from '@/library/powersync/AppSchema';
import { supabase } from '@/plugins/supabase';
import { usePowerSync } from '@journeyapps/powersync-vue';
import { ref } from 'vue';

const powerSync = usePowerSync();
const showPrompt = ref(false);
const setShowPrompt = (state: boolean): void => {
  if (state) listName.value = '';
  showPrompt.value = state;
};

const listName = ref('');

const createNewList = async () => {
  const session = await supabase.client.auth.getSession();
  const userID = session?.data.session?.user?.id;
  if (!userID) {
    throw new Error(`Could not create new lists, no userID found`);
  }

  const res = await powerSync.value.execute(
    `INSERT INTO ${LISTS_TABLE} (id, created_at, name, owner_id) VALUES (uuid(), datetime(), ?, ?) RETURNING *`,
    [listName.value, userID]
  );

  const resultRecord = res.rows?.item(0);
  if (!resultRecord) {
    throw new Error('Could not create list');
  }
};

const submit = () => {
  try {
    createNewList();
  } finally {
    setShowPrompt(false);
  }
};
</script>

// demos/nextjs-supabase-todolist/src/app/views/todo-lists/page.tsx
import { usePowerSync } from '@journeyapps/powersync-react';
import AddIcon from '@mui/icons-material/Add';
import {
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  TextField,
  styled
} from '@mui/material';
import Fab from '@mui/material/Fab';
import React from 'react';
import { NavigationPage } from '@/components/navigation/NavigationPage';
import { useSupabase } from '@/components/providers/SystemProvider';
import { TodoListsWidget } from '@/components/widgets/TodoListsWidget';
import { LISTS_TABLE } from '@/library/powersync/AppSchema';

export default function TodoListsPage() {
  const powerSync = usePowerSync();
  const supabase = useSupabase();

  const [showPrompt, setShowPrompt] = React.useState(false);
  const nameInputRef = React.createRef<HTMLInputElement>();

  const createNewList = async (name: string) => {
    const session = await supabase?.client.auth.getSession();
    const userID = session?.data.session?.user?.id;
    if (!userID) {
      throw new Error(`Could not create new lists, no userID found`);
    }

    const res = await powerSync.execute(
      `INSERT INTO ${LISTS_TABLE} (id, created_at, name, owner_id) VALUES (uuid(), datetime(), ?, ?) RETURNING *`,
      [name, userID]
    );

    const resultRecord = res.rows?.item(0);
    if (!resultRecord) {
      throw new Error('Could not create list');
    }
  };

  return (
    <NavigationPage title="Todo Lists">
      <Box>
        <S.FloatingActionButton onClick={() => setShowPrompt(true)}>
          <AddIcon />
        </S.FloatingActionButton>
        <Box>
          <TodoListsWidget />
        </Box>
        {/* TODO use a dialog service in future, this is just a simple example app */}
        <Dialog
          open={showPrompt}
          onClose={() => setShowPrompt(false)}
          PaperProps={{
            component: 'form',
            onSubmit: async (event: React.FormEvent<HTMLFormElement>) => {
              event.preventDefault();
              await createNewList(nameInputRef.current!.value);
              setShowPrompt(false);
            }
          }}
          aria-labelledby="alert-dialog-title"
          aria-describedby="alert-dialog-description"
        >
          <DialogTitle id="alert-dialog-title">{'Create Todo List'}</DialogTitle>
          <DialogContent>
            <DialogContentText id="alert-dialog-description">Enter a name for a new todo list</DialogContentText>
            <TextField sx={{ marginTop: '10px' }} fullWidth inputRef={nameInputRef} label="List Name" autoFocus />
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setShowPrompt(false)}>Cancel</Button>
            <Button type="submit">Create</Button>
          </DialogActions>
        </Dialog>
      </Box>
    </NavigationPage>
  );
}

namespace S {
  export const FloatingActionButton = styled(Fab)`
    position: absolute;
    bottom: 20px;
    right: 20px;
  `;
}
